addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.20")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.4.20")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.7")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.31")
